//  布局结构图片映射
export const layoutImgMap = {
  logicalStructure: () => import('../assets/img/structures/logicalStructure.png'),
  mindMap: () => import('../assets/img/structures/mindMap.png'),
  organizationStructure: () => import('../assets/img/structures/organizationStructure.png'),
  catalogOrganization: () => import('../assets/img/structures/catalogOrganization.png'),
  timeline: () => import('../assets/img/structures/timeline.png'),
  timeline2: () => import('../assets/img/structures/timeline2.png'),
  fishbone: () => import('../assets/img/structures/fishbone.png'),
  verticalTimeline: () => import('../assets/img/structures/verticalTimeline.png')
};


//  主题图片映射
export const themeMap = {
  default: import('../assets/img/themes/default.jpg'),
  classic: import('../assets/img/themes/classic.jpg'),
  minions: import('../assets/img/themes/minions.jpg'),
  pinkGrape: import('../assets/img/themes/pinkGrape.jpg'),
  mint: import('../assets/img/themes/mint.jpg'),
  gold: import('../assets/img/themes/gold.jpg'),
  vitalityOrange: import('../assets/img/themes/vitalityOrange.jpg'),
  greenLeaf: import('../assets/img/themes/greenLeaf.jpg'),
  dark2: import('../assets/img/themes/dark2.jpg'),
  skyGreen: import('../assets/img/themes/skyGreen.jpg'),
  classic2: import('../assets/img/themes/classic2.jpg'),
  classic3: import('../assets/img/themes/classic3.jpg'),
  classic4: import('../assets/img/themes/classic4.jpg'),
  classicGreen: import('../assets/img/themes/classicGreen.jpg'),
  classicBlue: import('../assets/img/themes/classicBlue.jpg'),
  blueSky: import('../assets/img/themes/blueSky.jpg'),
  brainImpairedPink: import('../assets/img/themes/brainImpairedPink.jpg'),
  dark: import('../assets/img/themes/dark.jpg'),
  earthYellow: import('../assets/img/themes/earthYellow.jpg'),
  freshGreen: import('../assets/img/themes/freshGreen.jpg'),
  freshRed: import('../assets/img/themes/freshRed.jpg'),
  romanticPurple: import('../assets/img/themes/romanticPurple.jpg'),
  simpleBlack: import('../assets/img/themes/simpleBlack.jpg'),
  courseGreen: import('../assets/img/themes/courseGreen.jpg'),
  coffee: import('../assets/img/themes/coffee.jpg'),
  redSpirit: import('../assets/img/themes/redSpirit.jpg'),
  blackHumour: import('../assets/img/themes/blackHumour.jpg'),
  lateNightOffice: import('../assets/img/themes/lateNightOffice.jpg'),
  blackGold: import('../assets/img/themes/blackGold.jpg'),
  autumn: import('../assets/img/themes/autumn.jpg'),
  avocado: import('../assets/img/themes/avocado.jpg'),
  orangeJuice: import('../assets/img/themes/orangeJuice.jpg'),
  oreo: import('../assets/img/themes/oreo.jpg'),
  shallowSea: import('../assets/img/themes/shallowSea.jpg'),
  lemonBubbles: import('../assets/img/themes/lemonBubbles.jpg'),
  rose: import('../assets/img/themes/rose.jpg'),
  seaBlueLine: import('../assets/img/themes/seaBlueLine.jpg'),
  neonLamp: import('../assets/img/themes/neonLamp.jpg'),
  darkNightLceBlade: import('../assets/img/themes/darkNightLceBlade.jpg'),
  morandi: import('../assets/img/themes/morandi.jpg'),
  classic5: import('../assets/img/themes/classic5.jpg'),
  dark3: import('../assets/img/themes/dark3.jpg'),
  dark4: import('../assets/img/themes/dark4.jpg'),
  cactus: import('../assets/img/themes/cactus.jpg')
}

// 公式列表
export const formulaList = [
  'a^2',
  'a_2',
  'a^{2+2}',
  'a_{i,j}',
  'x_2^3',
  '\\overbrace{1+2+\\cdots+100}',
  '\\sum_{k=1}^N k^2',
  '\\lim_{n \\to \\infty}x_n',
  '\\int_{-N}^{N} e^x\\, dx',
  '\\sqrt{3}',
  '\\sqrt[n]{3}',
  '\\sin\\theta',
  '\\log X',
  '\\log_{10}',
  '\\log_\\alpha X',
  '\\lim_{t\\to n}T',
  '\\frac{1}{2}=0.5',
  '\\binom{n}{k}',
  '\\begin{matrix}x & y \\\\z & v\\end{matrix}',
  '\\begin{cases}3x + 5y +  z \\\\7x - 2y + 4z \\\\-6x + 3y + 2z\\end{cases}'
]
